/**
* HTML web skeleton
*
* @return web page string
*/
String formHTML(){

  String form =""
"<html>\n"
"<head>\n"
  "<script type='text/javascript'>\n"
    "function onClick(value){\n"
      "document.querySelector('[name=\"freq\"]').value -= -value;\n"
      "document.getElementById('mainForm').submit();\n"
    "}\n"
  "</script>\n"
  "<style>\n"
    "body{\n"
      "text-align: center;\n"
      "font-size: 20px;\n"
    "}\n"
    "input[type=text]{\n"
      "width: 215px;\n"
      "padding: 8px;\n"
      "margin: 10px;\n"
      "margin-left: 10px;\n"
      "border: 1px solid rgba(0,0,0,0.25);\n"
    "}\n"
    "button[name=m1], button[name=p1]{\n"
      "background: #e74c3c;\n"
      "border: 1px solid rgba(0,0,0,0.125);\n"
    "}\n"
    "button[name=m01], button[name=p01]{\n"
      "background: #f39c12;\n"
      "border: 1px solid rgba(0,0,0,0.125);\n"
    "}\n"
    "button[name=m1]:hover, button[name=p1]:hover{\n"
      "background: #c0392b;\n"
    "}\n"
    "button[name=m01]:hover, button[name=p01]:hover{\n"
      "background: #e67e22;\n"
    "}\n"
    "button{\n"
      "margin: -3px;\n"
      "padding: 5px;\n"
      "color: white;\n"
      "font-weight: bold;\n"
    "}\n"
    "input[type=submit]{\n"
      "color: white;\n"
      "margin: -3px;\n"
      "padding: 5px;\n"
      "border: 1px solid rgba(0,0,0,0.125);\n"
      "background: #2ecc71;\n"
      "font-weight: bold;\n"
    "}\n"
    "input[type=submit]:hover{\n"
      "background: #27ae60;\n"
    "}\n"
    "form{\n"
      "position: absolute;\n"
      "transform: translate(-50%,-50%) scale(1.3);\n"
      "left: 50%;\n"
      "top: 50%;\n"
    "}\n"
    "@media only screen and (max-width: 998px) {\n"
      "form{\n"
        "position: absolute;\n"
        "transform: translate(-50%,-50%) scale(4);\n"
        "left: 50%;\n"
        "top: 50%;\n"
      "}\n"
    "}\n"
"\n"
  "</style>\n"
"</head>\n"
"<body>\n"
  "<form action='ctl' id='mainForm' method='get'>\n"
    "<br>\n"
    "<input type='text' name='freq' placeholder='Enter your strobe frequency here' value='"+server.arg("freq")+"'>\n"
    "<br>\n"
    "<button type='button' name='m1' onclick='onClick(-1)'>-1</button>\n"
    "<button type='button' name='m01' onclick='onClick(-0.1)'>-0.1</button>\n"
    "<input type='submit' value='Set Frequency'>\n"
    "<button type='button' name='p01' onclick='onClick(0.1)'>+0.1</button>\n"
    "<button type='button' name='p1' onclick='onClick(1)'>+1</button>\n"
  "</form>\n"
"</body>\n"
"</html>\n";

  return (form);
}